import {
  Loader2,
  Leaf,
  Plus,
  Zap,
  Building,
  Globe,
  BarChart,
  Search,
  Shield,
  LayoutDashboard,
  Folder,
  ShieldCheck,
  MessageSquare,
  PieChart,
  LogOut,
  ChevronRight,
  MapPin,
  Briefcase,
  FileText,
  Filter,
  Bookmark,
  Check,
  MoreVertical,
  Paperclip,
  Send,
  DollarSign,
  Settings,
  Handshake,
  Download,
  HardHat,
  AlertTriangle,
  Layers,
  Cpu,
  ArrowUpRight,
  LineChart,
  BarChart2,
  CheckCircle2,
  Lock,
  Database,
  ArrowRight,
  ArrowLeft,
  Droplet,
  Wind,
  Sun,
  Mail,
  ChevronDown,
  User,
  Info,
  Phone,
  Trash2,
  X,
} from "lucide-react";

export const Icons = {
  spinner: Loader2,
  close: X,
  plus: Plus,
  zap: Zap,
  building: Building,
  globe: Globe,
  barChart: BarChart,
  search: Search,
  shield: Shield,
  layoutDashboard: LayoutDashboard,
  folder: Folder,
  shieldCheck: ShieldCheck,
  messageSquare: MessageSquare,
  pieChart: PieChart,
  logout: LogOut,
  logOut: LogOut,
  chevronRight: ChevronRight,
  mapPin: MapPin,
  briefcase: Briefcase,
  fileText: FileText,
  filter: Filter,
  bookmark: Bookmark,
  check: Check,
  moreVertical: MoreVertical,
  paperclip: Paperclip,
  send: Send,
  dollar: DollarSign,
  dollarSign: DollarSign,
  settings: Settings,
  handshake: Handshake,
  download: Download,
  hardHat: HardHat,
  alert: AlertTriangle,
  alertTriangle: AlertTriangle,
  info: Info,
  layers: Layers,
  cpu: Cpu,
  arrowUpRight: ArrowUpRight,
  lineChart: LineChart,
  barChart2: BarChart2,
  checkCircle2: CheckCircle2,
  lock: Lock,
  database: Database,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  droplet: Droplet,
  wind: Wind,
  sun: Sun,
  mail: Mail,
  star: (props: any) => (
    <svg
      role="img"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  ),
  chevronDown: ChevronDown,
  user: User,
  trash: Trash2,
  logo: (props: any) => (
    <Leaf
      {...props}
    />
  ),
  google: (props: any) => (
    <svg
      role="img"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      fill="currentColor"
      {...props}
    >
      <path d="M12.48 10.92v3.28h7.84c-.24 1.84-.908 3.152-1.928 4.176-1.02 1.024-2.6 2.144-5.912 2.144-5.272 0-9.616-4.272-9.616-9.536s4.344-9.536 9.616-9.536c2.84 0 4.944 1.12 6.44 2.512l2.312-2.312C19.16 1.44 16.32 0 12.48 0 5.864 0 0 5.384 0 12s5.864 12 12.48 12c3.552 0 6.232-1.176 8.336-3.352 2.16-2.16 2.84-5.216 2.84-7.664 0-.744-.064-1.456-.184-2.112H12.48z" />
    </svg>
  ),
};

// Also export as individual components to fix the import errors in page.tsx
export {
  Loader2,
  Leaf,
  Plus,
  Zap,
  Building,
  Globe,
  BarChart,
  Search,
  Shield,
  LayoutDashboard,
  Folder,
  ShieldCheck,
  MessageSquare,
  PieChart,
  LogOut,
  ChevronRight,
  MapPin,
  Briefcase,
  FileText,
  Filter,
  Bookmark,
  Check,
  MoreVertical,
  Paperclip,
  Send,
  DollarSign,
  Settings,
  Handshake,
  Download,
  HardHat,
  AlertTriangle,
  Layers,
  Cpu,
  ArrowUpRight,
  LineChart,
  BarChart2,
  CheckCircle2,
  Lock,
  Database,
  ArrowRight,
  ArrowLeft,
  Droplet,
  Wind,
  Sun,
  Mail,
  ChevronDown,
  User,
  Info,
  Phone,
  Trash2,
};
