import {
  Loader2,
  Github,
  Chrome,
  Mail,
  MoreHorizontal,
  Plus,
  Search,
  Settings,
  User,
  LogOut,
  ChevronLeft,
  ChevronRight,
  LayoutDashboard,
  FolderOpen,
  MessageSquare,
  FileText,
  ShieldCheck,
  TrendingUp,
  Zap,
  Globe,
  DollarSign,
  AlertTriangle,
  CheckCircle2,
  Clock,
  Briefcase,
  Building2,
  Handshake,
  Shield,
  ArrowRight,
} from 'lucide-react';

export const Icons = {
  spinner: Loader2,
  gitHub: Github,
  google: Chrome,
  mail: Mail,
  more: MoreHorizontal,
  plus: Plus,
  search: Search,
  settings: Settings,
  user: User,
  logout: LogOut,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  dashboard: LayoutDashboard,
  projects: FolderOpen,
  messages: MessageSquare,
  documents: FileText,
  validation: ShieldCheck,
  trending: TrendingUp,
  energy: Zap,
  region: Globe,
  capital: DollarSign,
  warning: AlertTriangle,
  success: CheckCircle2,
  time: Clock,
  developer: Briefcase,
  investor: Building2,
  partner: Handshake,
  admin: Shield,
  arrowRight: ArrowRight,
};
